name: REVOlution
favicon: null
layout_spectrum: 0.19188454933464527
typography_spectrum: 0.8540550917387009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#46c5f0'
    - '#ffffff'
    - '#32586c'
    - '#4f7781'
    - '#45a7cb'
  brandStrength: 0.5685640985611826
  lightness: 0.33100162679329515
  saturation: 0.9719808122608811
  rhythmicContrast: 0.7030255293939263
purpose: []
